var App=function(){var iniciarTeclado=function(){AUI().use('transition',function(A){A.all('fieldset p span:last-child').addClass('last');});};var iniciarSlider=function(){if($('#isMobile').val()=="true")
{$('.flexslider').flexslider({animation:"slide",touch:"true"});}else{$('.flexslider').flexslider({animation:"slide",controlNav:"thumbnails",start:function(slider){$('body').removeClass('loading');$('.flex-nav-next > a, .flex-nav-prev > a').html('');}});}};var iniciarBusca=function(){$(".busca select option").eq(1).prop('selected',true);$('#_3_clearSearch').parent().append('<span class="search-result">Você procurou por: <strong class="blue">'+$('#_3_keywords').val()+'</strong>');$('#_3_keywords').parent().prepend('<h1> RESULTADO DE BUSCA</h1>');$('.busca > form > input[type="text"]').attr("placeholder","O que você busca?");$('.busca > form > input[type="text"]').css("margin-right","-25px");$('.busca > form').prepend('<div class="divClickBusca"> </div>');$(".divClickBusca").click(function(){$(this).parent().submit();});$(".topoMobile > ul > li.itemBusca").click(function(){if($(".buscaMobile > #busca").hasClass("buscaMobileInvisivel")){$(".buscaMobile > #busca").removeClass("buscaMobileInvisivel");}else{$(".buscaMobile > #busca").removeClass("buscaMobileVisivel");$(".buscaMobile > #busca").addClass("buscaMobileInvisivel");}});$("#busca > .busca > .iconMobile > img").click(function(){$(".buscaMobile > #busca").hasClass("buscaMobileVisivel");$(".buscaMobile > #busca").removeClass("buscaMobileVisivel");$(".buscaMobile > #busca").addClass("buscaMobileInvisivel");});};var iniciarMenuFlutuante=function(){var popup=$('#popupLogin');var nav=$('#menu_Principal');var scrolled=false;$(window).scroll(function(){if(110<$(window).scrollTop()&&!scrolled){nav.removeClass('hide').css('margin-top','0px');$('#toTop').show();nav.show();scrolled=true;if($("#menu_Principal").css('display')==='block'){popup.addClass('scrollPopup').animate({'margin-top':'-15px !important'});}}
if(110>$(window).scrollTop()&&scrolled){$('#toTop').hide();nav.hide();nav.addClass('hide').animate({'margin-top':'0px'});popup.addClass('scrollPopup').animate({'margin-top':'25px !important'});scrolled=false;}});};var iniciarTop=function(){$('#toTop').hide();$('#toTop').on('click',function(e){$('html,body').animate({scrollTop:0},'slow');});};var iniciarMenuMobile=function(){$('.menuMobile ').on('click',function(){if($('#banner').attr('data-state')==='neutral'){$('#banner').attr('data-state','slide-right');$('.navMenuMobile').attr('data-state','slide-right');}else{$('#banner').attr('data-state','neutral');$('.navMenuMobile').attr('data-state','neutral');}});};var iniciarTag=function(){if(navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/Android/i)){var viewportmeta=document.querySelector('meta[name="viewport"]');if(viewportmeta){if(screen.width>900){document.querySelector('meta[name="viewport"]').setAttribute("content","width=device-width, initial-scale=1.0");return false;}
if(screen.width<900&&screen.width>480){document.querySelector('meta[name="viewport"]').setAttribute("content","width=device-width, initial-scale=0.8");return false;}
if(screen.width<400){document.querySelector('meta[name="viewport"]').setAttribute("content","width=device-width, initial-scale=0.8");return false;}}}};var inicarRodape=function(){$('.blocoRodape > ul > li').each(function(index,value){if($(this).find('.subItem > ul > li').hasClass("selectedSegundo")){$(this).addClass('selected');}});};return{init:function(){iniciarMenuFlutuante();iniciarTop();iniciarBusca();iniciarMenuMobile();inicarRodape();iniciarSlider();iniciarTeclado();var tmbCaminho=$('#caminhoHome').val();if($('.breadcrumb-truncate').length!=0){$($('#breadcrumbs > ul> li')[0]).remove();$($('#breadcrumbs > ul> li')[0]).remove();$($('#breadcrumbs > ul> li > a')[0]).html('');$($('#breadcrumbs > ul> li > a')[0]).append('<img src="'+tmbCaminho+'" />');if($('#breadcrumbs > ul> li')[1]!=undefined){$($('#breadcrumbs > ul> li')[1]).remove();}
if($('#breadcrumbs > ul > li').length<=1){$('#breadcrumbs').remove();}
$('#breadcrumbs').show();}else{$($('#breadcrumbs > ul> li')[0]).remove();$($('#breadcrumbs > ul> li > a')[0]).html('');$($('#breadcrumbs > ul> li > a')[0]).append('<img src="'+tmbCaminho+'" />');if($('#breadcrumbs > ul> li')[1]!=undefined){$($('#breadcrumbs > ul> li')[1]).remove();}
if($('#breadcrumbs > ul > li').length<=1){$('#breadcrumbs').remove();}
$('#breadcrumbs').show();}},};}();function abrirModalThema(divConteudo,titulo,largura){var tmpTamanho=0;if(largura==null){if($('#isMobile').val()=="true"){tmpTamanho="100%";}else{tmpTamanho="920";}}else{tmpTamanho=largura;}
AUI().use('aui-modal',function(Y){var modal=new Y.Modal({centered:true,contentBox:divConteudo,draggable:false,render:'body',headerContent:titulo,resizable:false,width:tmpTamanho,modal:true,zIndex:10,}).render();});}